//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationDrawerPopUpMenu2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etap
    {
        public int IdEtap { get; set; }
        public string naimenovanieEtap { get; set; }
        public Nullable<System.DateTime> DataNachala { get; set; }
        public string Vajnost { get; set; }
        public int StepenGotovnosti { get; set; }
        public string ObimRabot { get; set; }
        public Nullable<int> Otvetstvenniy { get; set; }
        public Nullable<int> zadacha { get; set; }
    
        public virtual Sotrydniki Sotrydniki { get; set; }
        public virtual Zadacha Zadacha1 { get; set; }
    }
}
