//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationDrawerPopUpMenu2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agentstvoEntities : DbContext
    {
        public agentstvoEntities()
            : base("name=agentstvoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etap> Etap { get; set; }
        public virtual DbSet<Meneger> Meneger { get; set; }
        public virtual DbSet<meneger1> meneger1 { get; set; }
        public virtual DbSet<Otdel> Otdel { get; set; }
        public virtual DbSet<otdel1> otdel1 { get; set; }
        public virtual DbSet<Sotrydniki> Sotrydniki { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zadacha> Zadacha { get; set; }
    }
}
