//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationDrawerPopUpMenu2
{
    using System;
    using System.Collections.Generic;
    
    public partial class otdel1
    {
        public int IDotdel1 { get; set; }
        public int menegerid1 { get; set; }
        public string Naimenovanie1 { get; set; }
        public string zadacha { get; set; }
        public string sotrydniki { get; set; }
    
        public virtual meneger1 meneger1 { get; set; }
    }
}
